[package]
name = "gitters"
version = "0.1.0"
authors = ["Avik Das <avik.das@berkeley.edu>"]

[dependencies]
byteorder = "1.0.0"
chrono = "0.2"
docopt = "0.6"
errno = "0.2"
flate2 = "0.2"
lazy_static = "0.2"
libc = "0.2"
regex = "0.1"
rustc-serialize = "0.3"
